language: node_js
node_js:
  - "8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install

addons:
  chrome: stable

stages:
  - lint
  - test
  - name: build-development
    if: tag IS blank
  - name: build-release
    if: tag IS present

jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm test
    - stage: build-development
      script:
        - npm run build
    - stage: build-release
      script:
        - npm run build
